apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-service-config
data:
  MONGO_URL: "mongodb://execution-service-mongo:27017/execution_service"
  PORT: "3000"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
