apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
  labels:
    app: execution-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
    spec:
      containers:
      - name: execution-service
        image: guitxgomes/oficina-ms-execution-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: execution-service-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        readinessProbe:
          httpGet: { path: /health, port: 3000 }
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 3000 }
          initialDelaySeconds: 40
          periodSeconds: 15
